name: Create Release
on:
  push:
    branches: [ main ]
    paths:
      - 'CHANGELOG.md'
      - 'src/frontend/package.json'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'chore: prepare frontend release')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: npm i -fg corepack && corepack enable
    
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: 'src/frontend/package-lock.json'
    
    - name: Install changelogen
      run: |
        cd src/frontend
        npm install
    
    - name: Create release
      run: |
        cd src/frontend
        npm run release:create
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
