name: Frontend CI
on:
  push:
    branches: [ main ]
    paths:
      - 'src/frontend/**'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for changelogen
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: npm i -fg corepack && corepack enable
    
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: 'src/frontend/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd src/frontend
        npm install
    
    # Only run release preparation on main branch pushes
    - name: Check for release-worthy changes
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: check-changes
      run: |
        cd src/frontend
        # Check if there are any feat/fix/ui commits since last release
        if git log --oneline --grep="feat\|fix\|ui" --since="1 week ago" -- ./ | head -10 | grep -q .; then
          echo "has-releaseable-changes=true" >> $GITHUB_OUTPUT
        else
          echo "has-releaseable-changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Create release preparation PR
      if: steps.check-changes.outputs.has-releaseable-changes == 'true'
      run: |
        # Configure git user
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create a new branch for release preparation
        BRANCH_NAME="release/frontend-$(date +%Y%m%d-%H%M%S)"
        git checkout -b $BRANCH_NAME
        
        # Generate changelog and prepare release
        cd src/frontend
        npm run release:prepare
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit the changes
        git add CHANGELOG.md package.json
        git commit -m "chore: prepare frontend release"
        
        # Push the branch
        git push origin $BRANCH_NAME
        
        # Create PR using GitHub CLI
        gh pr create \
          --title "🚀 Frontend Release Preparation" \
          --body "This PR prepares a new frontend release based on recent changes.
          
          ## Changes Included
          - Updated CHANGELOG.md with recent frontend changes
          - Bumped version in frontend package.json
          
          ## Next Steps
          1. Review the changelog
          2. Merge this PR to trigger the release
          3. The release will be automatically created with a GitHub tag" \
          --base main \
          --head $BRANCH_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
